name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    Outputs: # Define outputs for the build job
      script-file: ${{ steps.publish.outputs.stepBuild-file }}      
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Publish js filename
        id: publish
      # Publish the filename of the built JavaScript file as step output variable
        run: find dist/assets/*.js -type f -execdir echo 'stepBuild-file={}' >> $GITHUB_OUTPUT ';' 
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files # Name of the artifact
          path: dist # Path to the directory containing the files to upload
          # path: |   # Paths to include in the artifact
          #   dist  
          #   package.json
          retention-days: 1
  deploy:
    needs: [build] # Specify that the deploy job depends on the build job
    runs-on: ubuntu-latest # Specify the runner for the deploy job
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist-files # Name of the artifact to download
      - name: List downloaded files
        run: ls
      - name: Read script filename from build job output
        run: echo "Script filename from build job: ${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
